version: '3.8'

services:
  api:
    build:
      context: ./api
    ports:
      - "5555:5555"
    restart: always
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=heroesDb
    depends_on:
      - db
    command: npm run start
    volumes:
      - ./api/:/app/
      - /app/node_modules
      - /app/dist
  front:
    build:
      context: ./front
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - api
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - ./front:/app
      - /app/node_modules

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heroesDb
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
